### ISSUE TITLE
TSIdentExprをASTNode内で使う必要はあるかどうか

### ISSUE THREAD

**Issue by sidepelican** [omochi/TypeScriptAST#10]
何らかのASTNodeが何らかのIdentifierを表現したい際に、現在`TSIdentExpr`を受け取るか`String`を受け取るか割れているように思います。

何らかのIdentifierを表示しようとしているASTNodeのうち

### `TSIdentExpr`を使っているもの

- TSCatchStmt
- TSMemberExpr

### `String`を使っているもの

- TSClassDecl
- TSFieldDecl
- TSFunctionDecl
- TSImportDecl
- TSInterfaceDecl（これはTSの機能なのでInterface名がIdentifierといえるかはよくわからない）
- TSMethodDecl
... など多数

`TSIdentType`を用いた場合はその文字列がIdentifierとして適正かどうか検査することができますが、特にそのような機能は必要ないと思うので全て`String`に寄せていいと思ったのですが、どうでしょうか。

**Comment by sidepelican** [comment]
`TSIdentExpr`になっているとASTVisitorからvisitされるのでimportが補完できるというメリットがある？
その場合全体的に`TSIdentExpr`に寄せるほうが正解かもしれない

**Comment by sidepelican** [comment]
宣言する側と使う側との区別をきちんとしないと、importがめっちゃ壊れそう。
スコープの検査も関わってくる？
結構難しいかもしれない・・・

**Comment by omochi** [comment]
TSIdentExprは式としての名前参照を意味していますね、その文字列が何を意味しているかの解決処理の対象になり、実行時に値として評価されます。
class宣言についてる名前などは名前を定義しているだけで、特に式ではないのでStringにしてます。
指摘の中だとTSCatchStmtの変数名定義部分がTSIdentExprなのは間違ってると思いました。

**Comment by sidepelican** [comment]
`TSMemberExpr`についても間違っていませんか？オブジェクトのプロパティ名はオブジェクトとプロパティ名の複合であれば値として評価されますが、プロパティ名単体では評価のしようがないと思います

**Comment by omochi** [comment]
たしかに。ドットの左側のbaseが一般のTSExprなのは良いとして、ドットの右側は、その式全体で意味が成り立つのでTSIdentExprではない、と考えた方が良いですね

**Comment by omochi** [comment]
@sidepelican 他に疑問点無ければcloseお願いします。
