### ISSUE TITLE
TSObjectTypeが関数を表せない

### ISSUE THREAD

**Issue by sidepelican** [omochi/TypeScriptAST#16]
現状、以下のようなコードを表すことができません。

```ts
type Foo = {
  f();
};
```

## 解決方法

まず、TSTypeにこのようなメソッド型の定義が存在しないので、`TSMethodType`の追加が必要になると思いました。
現状`TSFunctionType`は存在しますが、見た感じだと

```ts
type Foo = {
  f: () => void
}
```

こちらの表現を表してそうで、最初に挙げたアロー演算子を使わない表現とは違うようです。

`TSMethodType`を定義したあとのやり方は2つあると思います。

### A. TSObjectExpr同様にTSObjectType.Fieldをenum化する

単純です。TSMethodTypeの入力を専用に受け入れます。
Exprのときと違って`isOptional`などパラメータの重複が多くなりそうです。

後方互換性もありません

### B. 現状と同じインターフェースで、TSMethodTypeのときだけPrinterが特別処理する

これもまあ単純です。複雑さがPrinterに隠蔽されますが、大したことはないと思います。TSObjectType単体で見たときにMethodTypeを区別して持たないこと自体もそれはそれで自然だと思います。
こっちは後方互換性があります。

## その他

- `TSFunctionType` がアロー式なのは `TSFunctionDecl`と対応が取れてないように感じました。アロー式を表すなら`TSClosureExpr`に合わせて`TSClosureType`がいいかと思いました

**Comment by omochi** [comment]
Aのほうが望ましいと思います。
`TSObjectType` がサポートすべきASTの表現能力において、
`TSObjectType.Field` が `<name>: <type>` の形式しか考慮していない事が問題の根幹だと思うからです。

B の方式の場合は、
`TSObjectType.Field` の `.name` が `TSMethodType` がもつ `.name` と重複して、
捨てる事になるのがおかしいと思います。

Aで、`TSObjectExpr` と同様に `case method(TSMethodType)` とするのが良いと思います。

> Exprのときと違ってisOptionalなどパラメータの重複が多くなりそうです。

ここはよくわかりませんでした、どのような重複が起きますか？

互換性は壊れてもいいと思います、
影響を受ける人数が限られている今のうちに、
正しい設計に寄せるほうがメリットが大きいと思います。

---

ところで、`TSClassDecl` については、 `TSFieldDecl` と `TSMethodDecl` を含む構造になっていますが、
`TSObjectExpr` の `case member` は `TSMethodDecl` を含むようにしているので、
同様に `case field` も `TSFieldDecl` を掴むようにしたほうがいいかもしれません。

それで、`TSObjectType` についても、 `TSMethodType` と `TSFieldType` を掴むほうが一貫性があってわかりやすい？

---

`TSFunctionType` についてですが、
TypeScriptにおいて「関数型」は「アロー式」で書く、という定義に合わせました。
https://www.typescriptlang.org/docs/handbook/2/functions.html#function-type-expressions
`TSClosureType` としてしまうと、クロージャ型が関数型とは区別されているような印象を受けて違和感がありますが・・・

ただ、仮に `function` キーワードを使って関数型を記述できる文法が存在した場合を考えると、
そちらに `TSFunctionType` という名前を当てて、 アロー式のほうは `TSClosureType` としたいですね。
見た目ベースの一貫性を重視して `TSClosureType` に変更しても良いと思います。

**Comment by sidepelican** [comment]
B方式の場合において、`TSMethodType`は名前を持たないので、`name`を捨てることにはならないと思います。
isOptionalの重複とはつまり

```swift
    enum Field {
        case named(name: String, isOptional: Bool = false, value: any TSExpr)
        case method(isOptional: Bool = false, TSMethodDecl)
    }
```

こうなるということですね。まあ大したことではないと思います

**Comment by sidepelican** [comment]
> 同様に case field も TSFieldDecl を掴むようにしたほうがいいかも

これは`protocol TSFieldType` というものを新設するということですか？
普通のフィールドに`name()`タイプの関数型を間違って使えないようにするためには、`TSMethodType`を`TSType`にしないほうがいいかもしれませんね、`TSMethodType`はTSIntersectionTypeなどで使えない型であるため区別が必要に感じました。その場合`TSMethodType`という専用のASTNode自体がいらなくて、TSObjectTypeが専用で構造を持っているだけでいいのかも？

**Comment by sidepelican** [comment]
> TypeScriptにおいて「関数型」は「アロー式」で書く、という定義

これは知りませんでした。なるほど。
ただ現状の `TSFunctionDecl`が見た目を意識した命名であることを考えると、同様に見た目ベースでいいんじゃないかと思いました

**Comment by omochi** [comment]
```ts
{
  f?();
}
```

↑上記のコードにおいて、

B方式の場合は `TSMethodType` は `()` の部分を受け持って、 `f` と `?` の部分は `TSObjectType.Field` が受け持つという事ですね。

A方式で、 `f` と `?` も、 `TSMethodType` の中で持つのがきれいな気がします。
`TSMethodDecl` が name を含むこととも対応してわかりやすそう。

**Comment by omochi** [comment]
> これはprotocol TSFieldType というものを新設するということですか？

`struct TSFieldType` を新設して、

```swift
enum TSObjectType.Field {
  case field(TSFieldType)
  case method(TSMethodType)
}
```

とする案です。

---

> 普通のフィールドにname()タイプの関数型を間違って使えないようにするためには、TSMethodTypeをTSTypeにしないほうがいいかもしれませんね、TSMethodTypeはTSIntersectionTypeなどで使えない型であるため区別が必要に感じました。その場合TSMethodTypeという専用のASTNode自体がいらなくて、TSObjectTypeが専用で構造を持っているだけでいいのかも？

これは悩ましい部分なんですよね。

同じ問題が `TSFieldDecl` と `TSMethodDecl` にもあって、
これらは `TSClassDecl` と `TSInterfaceDecl` の中にしか出現してはいけないのですが、
それを静的に制約できていません。

`TSObjectType` が専用の内部構造で持っている場合だと、
同じ形のコードが、(まさに、classとinterfaceのように)他の部分でも出現する場合に問題になります。

**Comment by sidepelican** [comment]
う〜〜ん悩ましいですね。
TSClassDeclとTSInterfaceDeclは中に入るものの幅が広いので口をゆるくしたいですが、TSObjectTypeだと（今思いつく限りでは）2つしかないので、仮に同じ形のコードが他所で出てくるとしても同じようなものを定義すればよさそう。

個人的には`any TSType`としては使えないのに`Type`の名前を持つ`TSFieldType`と`TSMethodType`を用意するのが微妙に思えてきました。
`Decl`はあんまり他と組み合わさることがないですけど、`Type`は結構複雑な構造を持てるので。

Typeというsuffixを違うのにすればいいだけの話かもしれないです

**Comment by omochi** [comment]
> TSObjectTypeだと（今思いつく限りでは）2つしかないので、仮に同じ形のコードが他所で出てくるとしても同じようなものを定義すればよさそう。

そうですね。`TSObjectType` が 子供として `[any TSType]` を持てるようにするのは緩めすぎだと思います。

> 仮に同じ形のコードが他所で出てくるとしても同じようなものを定義すればよさそう

これは再利用すべきだとは思います。VisitorやPrinterなど、いろいろなところで実装が繰り返してしまうので。

> Typeというsuffixを違うのにすればいいだけ

Type suffixを与えず `TSType` との継承関係も持たせないのはありだと思います。
ただ、型コンテキストで使われるASTノードである、というニュアンスは与えたほうが良い気がします。

`TSFieldTypeNode`, `TSMethodTypeNode` とか？

**Comment by sidepelican** [comment]
書いてて気づいたんですが、新設せずとも既存のDeclとほぼ同じなので

```swift
    public enum Field {
        case field(TSFieldDecl)
        case method(TSMethodDecl) // TSMethodDeclにisOptional: Boolを追加する
    }
```

でいいんじゃないでしょうか？
実装がかなり共通するし、役割的にも既存部分の使い方と同じだから問題ない気がする？

**Comment by omochi** [comment]
Printerは問題なく動きそうですね。
ScanDependencyが特に問題無く実装できそうなら良いと思います。
